trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  frontendDirectory: 'frontEnd/andromedaUI'  # Folder containing Angular app 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Ensure the Node.js version matches your Angular app requirements
  displayName: 'Install Node.js'

- script: |
    cd $(frontendDirectory)
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular CLI and Dependencies'

- script: |
    cd $(frontendDirectory)
    npm run build --prod
  displayName: 'Build Angular App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/frontEnd/andromedaUI/dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'Copy Files to Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'
